import { defineStore } from 'pinia'

export const useIkaintroubleC = defineStore('ikaintroublec', {
    state: () => ({
        prize: [
            {
                unit: '1隊',
                title: '冠軍賞',
                image: 'prize/ikaintrouble-c/bm.jpg',
                sponsor: '布喵ᔦꙬᔨ熱情贊助 ',
                rule: '落難杯3冠軍隊伍',
                luckysquid: '魷魚朋友愛好者',
                url: 'https://twitter.com/791218Meow/status/1596821260855832577',
            },
            {
                unit: '1隊',
                title: '亞軍賞',
                image: 'prize/ikaintrouble-c/polero.jpg',
                sponsor: 'Polero熱情贊助 ',
                rule: '落難杯3亞軍隊伍',
                luckysquid: '神di謀殺物語 vol.4',
                url: 'https://twitter.com/Polero_light/status/1601214460341129218',
            },
            {
                unit: '1位',
                title: '控場我來賞',
                image: 'prize/ikaintrouble-c/omurice.jpg',
                sponsor: 'Omurice炸黑輪熱情贊助 ',
                rule: '任一場次獲得真格區域前線把控 No.1的金牌即可抽獎',
                luckysquid: 'りょうすけ',
                url: 'https://twitter.com/yoyo091600/status/1594241330020225026',
            },
            {
                unit: '1位',
                title: '教練紅牌賞',
                image: 'prize/ikaintrouble-c/feng.jpg',
                sponsor: '粉粿熱情贊助 ',
                rule: '由所有參賽者票選最用心、最喜歡的教練獲獎',
                luckysquid: '音無',
                url: 'https://twitter.com/fenguooooo/status/1620050366820937729',
            },
            {
                unit: '2位',
                title: '進步最多賞',
                image: 'prize/ikaintrouble-c/pupu.jpg',
                sponsor: '噗噗噗噗噗噗噗熱情贊助 (繪師: Naum)',
                rule: '每個隊長提供一名該隊裡進步幅度最大的隊員，從20個人裡抽兩個獲獎',
                luckysquid: 'sola / PoiLee672',
                url: 'https://twitter.com/SplatooNaum/status/1627249212839849984',
            },
            {
                unit: '1位',
                title: '手刀賞',
                image: 'prize/ikaintrouble-c/nishi.jpg',
                sponsor: 'NISHI熱情贊助 ',
                rule: '第一個成功報名的玩家',
                luckysquid: '辣啦',
                url: 'https://twitter.com/yunxd/status/1603213259246829568',
            },
            {
                unit: '1位',
                title: '螺慢地剋賞',
                image: 'prize/ikaintrouble-c/turtle.jpg',
                sponsor: '烏龜熱情贊助 ',
                rule: '比賽期間拿鸚鵡螺且戰績有出現2跟7即可獲獎，如多人則擁有較多7的人獲獎',
                luckysquid: '佐佐',
                url: 'https://twitter.com/turtle8338/status/1614216386993352705',
            },
            {
                unit: '3位',
                title: '如果通通沒有賞',
                image: 'prize/ikaintrouble-c/lami.jpg',
                sponsor: '樂米得海味熱炒店熱情贊助 ',
                rule: '未獲得任何獎項的人即可參與抽獎',
                luckysquid: 'MuG〆[Rios] / 貓奴胖胖 / 泰勒',
                url: 'https://twitter.com/jupen5004/status/1595388647229992960',
            },
            {
                unit: '1位',
                title: '最佳輔助獎',
                image: 'prize/ikaintrouble-c/empty.jpg',
                sponsor: '連雅熱情贊助 ',
                rule: '任一場贏得比賽且獲得三個銀牌即可抽獎',
                luckysquid: '辣啦',
                url: 'https://twitter.com/yunxd/status/1595265512677990401',
            },
            {
                unit: '1位',
                title: '名牌賞',
                image: 'prize/ikaintrouble-c/chicken.jpg',
                sponsor: '雞腿 熱情贊助 ',
                rule: '贊助商最鍾意的名牌獲獎',
                luckysquid: '樂米得海味熱炒店',
                url: 'https://twitter.com/SnakeWolf/status/1631289367036657671',
            },
            {
                unit: '1位',
                title: '行動B控賞',
                image: 'prize/ikaintrouble-c/shiro.jpg',
                sponsor: 'シロ熱情贊助 (繪師:唯Yui)',
                rule: '任一場次獲得同伴跳躍目標No.1 的金牌即可抽獎',
                luckysquid: 'D-Tī',
                url: 'https://twitter.com/shiro_ika_/status/1597200505049972736',
            },
            {
                unit: '1位',
                title: 'SSR卡包賞',
                image: 'prize/ikaintrouble-c/lala.jpg',
                sponsor: '辣啦熱情贊助 ',
                rule: '比賽期間勝利姿勢選用占地鬥士之姿的玩家即可抽獎',
                luckysquid: '阿包',
                url: 'https://twitter.com/ilixBxili/status/1596140311952371715',
            },
            {
                unit: '1位',
                title: '差點慢了賞',
                image: 'prize/ikaintrouble-c/cz.jpg',
                sponsor: '雲畝熱情贊助',
                rule: '最後一位成功報名選手的玩家即可獲獎',
                luckysquid: 'towlee',
                url: '',
            },
            {
                unit: '1位',
                title: '金牌我發賞',
                image: 'prize/ikaintrouble-c/loose.jpg',
                sponsor: '白松熱情贊助 ',
                rule: '任一場次獲得刷新最佳計數（金牌） 即可抽獎',
                luckysquid: 'LWY奈奈',
                url: 'https://twitter.com/Sh1r0_001/status/1596131129807237121',
            },
            {
                unit: '1位',
                title: '你今天52了嗎賞',
                image: 'prize/ikaintrouble-c/aa.jpg',
                sponsor: 'AA熱情贊助 (繪師:琉璃紺)',
                rule: '1.拿52且單局剛好殺五個人且死兩次 2.備案: 若條件1無人達成，則當局只要擊殺與死亡分別為5或2(可互換)，即可參與抽獎',
                luckysquid: '你要喝飲料嗎',
                url: 'https://twitter.com/AAwahaspla/status/1600320559736590337',
            },
            {
                unit: '1隊',
                title: '超可愛賞',
                image: 'prize/ikaintrouble-c/eru1.jpg',
                sponsor: 'エル熱情贊助 ',
                rule: '隊伍全員髮型、服裝(帽子、衣服、鞋子)其中之一統一即可獲獎',
                luckysquid: '雨天就是要吃四公升壽司飯糰',
                url: 'https://twitter.com/ooluannoo/status/1607938929935937537',
            },
            {
                unit: '1隊',
                title: '@演算法賞',
                image: 'prize/ikaintrouble-c/madtaco.jpg',
                sponsor: 'MadTaco熱情贊助 ',
                rule: '大會最喜歡的隊伍名可獲獎',
                luckysquid: '炸襪滷豆焦啦焦啦焦啦',
                url: 'https://twitter.com/roy80225/status/1596163583347675136',
            },
            {
                unit: '1隊',
                title: '努力不懈賞',
                image: 'prize/ikaintrouble-c/vanto.jpg',
                sponsor: 'Vanto熱情贊助 ',
                rule: '初賽積分最低的隊伍可抽獎',
                luckysquid: '悠Miss米紅茶一號店',
                url: 'https://twitter.com/Vanto0320/status/1605085079986139136',
            },
            {
                unit: '1位',
                title: '超新星獎',
                image: 'prize/ikaintrouble-c/eru2.jpg',
                sponsor: 'エル熱情贊助 ',
                rule: '比賽期間最引人注目、表現最優異的三代新人',
                luckysquid: 'JSON',
                url: '',
            },
            {
                unit: '3位',
                title: '新人早鳥賞',
                image: 'prize/ikaintrouble-c/dada.jpg',
                sponsor: 'dada熱情贊助 ',
                rule: '最早報名的前三個三代玩家',
                luckysquid: '國鈞',
                url: '',
            },
            {
                unit: '2位',
                title: '鍋蓋魚賞',
                image: 'prize/ikaintrouble-c/rios.jpg',
                sponsor: 'Rios熱情贊助 ',
                rule: '比賽期間髮型為秀托頭(齊瀏海)者即可參加抽獎',
                luckysquid: '阿澐 / りょうすけ',
                url: '',
            },
            {
                unit: '1位',
                title: '贊助商最大～賞',
                image: 'prize/ikaintrouble-c/taylor.jpg',
                sponsor: 'Taylor熱情贊助 ',
                rule: '從贊助商裡抽出一位，限港台玩家',
                luckysquid: '布喵',
                url: '',
            },
            {
                unit: '1位',
                title: '無脊椎相談賞',
                image: 'prize/ikaintrouble-c/invert.jpg',
                sponsor: '無脊椎相談所熱情贊助 ',
                rule: '從選手及贊助商中抽出一位',
                luckysquid: 'N3phthys',
                url: '',
            },
            {
                unit: '1隊',
                title: '整場我最塗賞',
                image: 'prize/ikaintrouble-c/dora.jpg',
                sponsor: '朵拉熱情贊助 ',
                rule: '所有隊員該場P數加起來最大的得獎（擊殺數前面一欄 4個隊員的p數加起來）',
                luckysquid: '爆炸頭棉花糖遊戲還好',
                url: '',
            },
            {
                unit: '2隊',
                title: '德州撲克賞',
                image: 'prize/ikaintrouble-c/alpha.jpg',
                sponsor: '阿嚕法熱情贊助 ',
                rule: '1.全隊戰績(擊殺、助殺、死亡)符合鐵支(例如6666)，且加總分數最高者可獲獎 2.全隊戰績(擊殺、助殺、死亡)符合兩個對子(例如6622)，且加總分數最高者可獲獎 3.全隊戰績(擊殺、助殺、死亡)符合順子(例如9876)，且加總分數最"低"者可獲獎',
                luckysquid: '爆炸頭棉花糖遊戲還好 / 為什麼我們四個不能一起做瘋狗',
                url: '',
            },
        ],
        youtuber: [
            'aa','taylor',
           'roro', 'rita',
           'soya', 'dejavu'
        ],
        navlink: [
            {
                title: '比賽章程',
                link:'#theme'
            },
            {
                title: '賽制',
                link:'#contest'
            },
            {
                title: '大會獎品',
                link:'#award'
            },
            {
                title: '工作人員',
                link:'#staff'
            },
            {
                title: '聯絡我們',
                link:'https://discord.gg/VTjUQkB9uv'
            },
        ],
    })
})